project: 
  type: default
  output-dir: reports

date: 2025-07-02
date-format: "DD-MM-YYYY"

format: 
  revealjs: 
    theme: default
    embed-resources: true
    width: 1280
    height: 720
    slide-number: true
    execute:
      eval: true
      echo: false
      warning: false
      message: false
    progress: true
    fig-responsive: true
    pdf-export: true
    css: styles-revealjs.css